### ISSUE TITLE
一点美观性问题

### ISSUE THREAD

**Issue by Evans-lx** [Ori-Replication/obsidian-math-indicator-changer#2]
数学公式和中文文字距离太近会显得太过紧凑，观感不好。可不可以在前后的$符号和文字之间加一个空格，比如说把'\\('和‘\\)'替换成'\space\$'和'\$\space'

**Comment by Ori-Replication** [comment]
据我观察，一般ChatGPT在生成行内公式的时候，实际上 \\( 和 )\的前后都是有空格的。请问你使用的是哪种语言模型呢？我可以去看一下，然后试着加个开关？

**Comment by Evans-lx** [comment]
感谢回复。我用的也是ChatGPT。可能它生成的公式形式不是固定的？
